import { lazy } from 'react';

export const lazyRoutes = {
  public: {
    Home: lazy(() => import('../features/public/pages/Home')),
    ServicesPage: lazy(() => import('../features/public/pages/ServicesPage')),
    ServiceCategoryPage: lazy(() => import('../features/public/pages/ServiceCategoryPage')),
    HowItWorks: lazy(() => import('../features/public/pages/HowItWorks')),
    BecomeProvider: lazy(() => import('../features/public/pages/BecomeProviderPage')),
    ProviderDetail: lazy(() => import('../features/public/pages/ProviderDetailPage')),
    About: lazy(() => import('../features/public/pages/About')),
    Contact: lazy(() => import('../features/public/pages/Contact')),
    Unauthorized: lazy(() => import('../features/public/pages/UnauthorizedPage')),
    ServerError: lazy(() => import('../features/public/pages/ServerErrorPage')),
    Maintenance: lazy(() => import('../features/public/pages/MaintenancePage')),
    Terms: lazy(() => import('../features/public/pages/TermsPage')),
    Privacy: lazy(() => import('../features/public/pages/PrivacyPage')),
    ServiceDetails: lazy(() => import('../features/services/pages/ServiceDetails')),
  },
  auth: {
    Login: lazy(() => import('../features/auth/pages/Login')),
    Register: lazy(() => import('../features/auth/pages/Register')),
    CustomerRegister: lazy(() => import('../features/auth/pages/CustomerRegister')),
    ProviderRegister: lazy(() => import('../features/auth/pages/ProviderRegister')),
    VerifyOtp: lazy(() => import('../features/auth/pages/VerifyOtp')),
    ForgotPassword: lazy(() => import('../features/auth/pages/ForgotPassword')),
    ResetPasswordOtp: lazy(() => import('../features/auth/pages/ResetPasswordOtp')),
    ResetPassword: lazy(() => import('../features/auth/pages/ResetPassword')),
  },
  customer: {
    Dashboard: lazy(() => import('../features/customer/pages/CustomerDashboard')),
    Notifications: lazy(() => import('../features/customer/pages/CustomerNotifications')),
    Services: lazy(() => import('../features/services/pages/ServiceList')),
    CreateBooking: lazy(() => import('../features/booking/pages/CreateBooking')),
    Bookings: lazy(() => import('../features/customer/pages/CustomerBookings')),
    Addresses: lazy(() => import('../features/customer/pages/CustomerAddresses')),
    BookingDetails: lazy(() => import('../features/customer/pages/CustomerBookingDetails')),
    BookingTracking: lazy(() => import('../features/booking/pages/TrackBooking')),
    Payments: lazy(() => import('../features/customer/pages/CustomerPayments')),
    PaymentDetails: lazy(() => import('../features/customer/pages/CustomerPaymentPage')),
    Receipts: lazy(() => import('../features/payment/pages/CustomerReceiptsPage')),
    ReceiptDetails: lazy(() => import('../features/payment/pages/CustomerReceiptDetailsPage')),
    Reviews: lazy(() => import('../features/customer/pages/CustomerReviews')),
    Profile: lazy(() => import('../features/customer/pages/CustomerProfile')),
  },
  provider: {
    Dashboard: lazy(() => import('../features/provider/pages/ProviderDashboard')),
    Notifications: lazy(() => import('../features/provider/pages/ProviderNotifications')),
    Availability: lazy(() => import('../features/provider/pages/ProviderAvailabilityPage')),
    NearbyJobs: lazy(() => import('../features/provider/pages/NearbyJobsPage')),
    AssignedJobs: lazy(() => import('../features/provider/pages/AssignedJobsPage')),
    AssignedJobDetails: lazy(() => import('../features/provider/pages/ProviderJobDetails')),
    Jobs: lazy(() => import('../features/provider/pages/ProviderJobs')),
    JobDetails: lazy(() => import('../features/provider/pages/ProviderJobDetails')),
    Schedule: lazy(() => import('../features/provider/pages/ProviderSchedule')),
    Earnings: lazy(() => import('../features/provider/pages/ProviderEarnings')),
    Reviews: lazy(() => import('../features/provider/pages/ProviderReviews')),
    Profile: lazy(() => import('../features/provider/pages/ProviderProfile')),
    Verification: lazy(() => import('../features/provider/pages/ProviderVerification')),
  },
  admin: {
    Dashboard: lazy(() => import('../features/admin/pages/AdminDashboard')),
    Users: lazy(() => import('../features/admin/pages/AdminUsers')),
    Providers: lazy(() => import('../features/admin/pages/AdminProviders')),
    Bookings: lazy(() => import('../features/admin/pages/AdminBookings')),
    BookingDetails: lazy(() => import('../features/admin/pages/AdminBookingDetails')),
    Services: lazy(() => import('../features/admin/pages/AdminServices')),
    Categories: lazy(() => import('../features/admin/pages/AdminCategories')),
    Payments: lazy(() => import('../features/admin/pages/AdminPayments')),
    Receipts: lazy(() => import('../features/payment/pages/AdminReceiptsPage')),
    ReceiptDetails: lazy(() => import('../features/payment/pages/AdminReceiptDetailsPage')),
    Support: lazy(() => import('../features/admin/pages/AdminSupport')),
    AuditLogs: lazy(() => import('../features/admin/pages/AdminAuditLogs')),
    Reports: lazy(() => import('../features/admin/pages/AdminReports')),
    Reviews: lazy(() => import('../features/admin/pages/AdminReviews')),
    Notifications: lazy(() => import('../features/admin/pages/AdminNotifications')),
    Analytics: lazy(() => import('../features/admin/pages/AdminAnalytics')),
    Settings: lazy(() => import('../features/admin/pages/AdminSettings')),
  },
};
